// STEP 1: IN THIS ASSIGNMENT, THINK ABOUT THE RELATIONSHIP BETWEEN HTML AND JS FOR YOUR SEARCH. LOOK INSIDE OF YOUR HTML FILE AS WELL FOR THIS -- YOU WILL NEED A FUNCTION THAT WILL HANDLE YOUR CHANGE EVENT AS A TIP. INSIDE OF THIS SEARCH FUNCTION, YOU WILL NEED TO CREATE A CARD(S) THAT WILL DISPLAY THE SEARCH TERM YOU PROVIDED THROUGH THE MIRRIAM WEBSTER COLLEGIATE DICTIONARY API. LETS DO THIS!!!!

// STEP 2: USE AXIOS AND SEND A GET REQUEST TO THE FOLLOWING:

// https://www.dictionaryapi.com/api/v3/references/collegiate/json/volume?key=blah

// where 'volume' is the search term word you are providing and where 'blah' is the api key provided to you on signup for the api.

// STEP 3: CREATE A FUNCTION THAT WILL ACCEPT THIS DATA FROM THE API AND CREATE A COMPONENT THAT RETURNS A DOM ELEMENT STRUCTURE OF YOUR CHOOSING FROM THE DATA:

// STEP 4: PASS THE DATA, CREATING A NEW COMPONENT FOR EACH WORD, AND ADD IT TO THE DOM

// STEP 5: NOW THAT THIS COMPONENT IS HERE, MAKE ANOTHER COMPONENT FOR THE TRANSLATIONS AND ITS SEARCH FUNCTION. MAKE AN APPROPRIATE GET REQUEST FROM THE SPANISH DICTIONARY API. IF YOU ARE UNSURE HOW TO FIND THIS LOOK AT THE DOCUMENTATION FOR THE API. ADD THIS COMPONENT TO THE DOM AS WELL. 
